# Generated by Django 4.2 on 2024-10-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0007_commentmodel_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='item',
        ),
    ]
