# Generated by Django 4.2 on 2024-10-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0008_remove_commentmodel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rkfood_app.menuitems'),
            preserve_default=False,
        ),
    ]
