# Generated by Django 4.2 on 2024-10-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0010_cart_orderitem_delete_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
