# Generated by Django 4.2 on 2024-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0016_alter_order_order_status_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('credit card', 'credit card'), ('online', 'online')], max_length=20),
        ),
    ]
