# Generated by Django 4.2 on 2024-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0018_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('received', 'received'), ('ready', 'ready'), ('delivered', 'delivered')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
