# Generated by Django 4.2 on 2024-10-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0019_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_title',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('beverages', 'beverages')], default='Breakfast', max_length=10),
        ),
    ]
