# Generated by Django 4.2 on 2024-10-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0020_alter_menu_menu_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('rating', models.CharField(choices=[('poor', 'poor'), ('fair', 'fair'), ('good', 'good'), ('very good', 'very good'), ('excellent', 'excellent')], max_length=10)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
