# Generated by Django 4.2 on 2024-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0023_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('1', 'poor'), ('2', 'fair'), ('3', 'good'), ('4', 'very good'), ('5', 'excellent')], max_length=10),
        ),
    ]
