# Generated by Django 4.2 on 2024-10-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0029_alter_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
