# Generated by Django 4.2 on 2024-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0030_alter_feedback_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('ready', 'ready'), ('delivered', 'delivered')], max_length=15),
        ),
    ]
