# Generated by Django 4.2 on 2024-10-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0031_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('placed', 'placed'), ('confirmed', 'confirmed'), ('ready', 'ready'), ('delivered', 'delivered')], max_length=15),
        ),
    ]
