# Generated by Django 4.2 on 2024-10-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0032_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='set_default',
            field=models.BooleanField(default=False),
        ),
    ]
