# Generated by Django 4.2 on 2024-10-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0036_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('recent', 'Recent'), ('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'failed')], max_length=20),
        ),
    ]
