# Generated by Django 4.2 on 2024-10-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0037_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='food_type',
            field=models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], default=0, max_length=8),
            preserve_default=False,
        ),
    ]
