# Generated by Django 4.2 on 2024-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0039_restaurant_city_alter_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('recent', 'Recent'), ('past', 'past'), ('pending', 'Pending'), ('failed', 'failed')], max_length=20),
        ),
    ]
