# Generated by Django 4.2 on 2024-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0044_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
